[build]
  base = "artifacts/erp-simplificado"
  command = "pnpm run build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "https://estoque-wvfr.onrender.com/api/:splat"
  status = 200
  force = true